name: Build and deploy Node.js app to Azure Web App - itmd547-nocobase

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Enable Corepack (ensures correct Yarn version)
        run: corepack enable

      - name: Set Yarn network timeout
        run: yarn config set network-timeout 600000

      - name: yarn install and build
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AE4933D15EF44C91A1607D9B3B3517BA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4AD8AA1DD47949E19BEB9FAF6E926E5E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6F625E0D2F1D494BA9B5D5C07ED8205B }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'itmd547-nocobase'
          slot-name: 'Production'
          package: .
